name: Pull request
on:
  pull_request:
    branches: [ master, main, test**, dev** ]

jobs:
  Integration-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Node.js packages
        run: npm install
      - name: Build
        if: ${{ success() }}
        run: npm run build
      - name: Test
        if: ${{ success() }}
        run: npm run test